version: "3"

services:
  apache-debian:
    build:
      context: .
      dockerfile: ./debian.dockerfile
    command: sudo systemctl enable --now cockpit.socket
    restart: always
    ports: 
      - 80:80